version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - flask

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - ./backend/.env
      - FLASK_URL=http://flask:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./media:/app/media
      - ./final:/app/final
    depends_on:
      - flask
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  flask:
    build:
      context: ./downloader
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./downloader:/app
      - ./media:/app/media
  
volumes:
  media:
    driver: local
  final:
    driver: local